package:
  name: mercurial
  version: "6.8"
  epoch: 0
  description: "Scalable distributed SCM tool"
  target-architecture:
    - x86_64
    - aarch64
  copyright:
    - license: GPL-2.0-or-later
  dependencies:
    provider-priority: 0
    runtime:
      - python3

vars:
  pypi-package: mercurial

data:
  - name: py-versions
    items:
      3.10: "310"
      3.11: "311"
      3.12: "312"

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - gettext-dev
      - py3-supported-flit-core
      - py3-supported-gpep517
      - py3-supported-pip
      - py3-supported-python
      - py3-supported-python-dev
      - py3-supported-setuptools
      - py3-supported-wheel
      - python3
      - wolfi-base
      - zlib-dev
  environment:
    # This is needed to work around the error "ValueError: ZIP does not support timestamps before 1980"
    SOURCE_DATE_EPOCH: 315532800

pipeline:
  - uses: fetch
    with:
      uri: https://www.mercurial-scm.org/release/mercurial-${{package.version}}.tar.gz
      expected-sha256: 08e4d0e5da8af1132b51e6bc3350180ad57adcd935f097b6d0bc119a2c2c0a10

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: ${{vars.pypi-package}} installed for python${{range.key}}
    pipeline:
      - runs: |
          pip${{range.key}} install . --no-deps --prefix=/usr --root=${{targets.subpkgdir}}
    dependencies:
      provides:
        - py3-${{vars.pypi-package}}
      runtime:
        - python-${{range.key}}
      provider-priority: ${{range.value}}
