package:
  name: ruby3.2-parser
  version: 3.3.3.0
  epoch: 0
  description: Run any code in parser Processes.
  target-architecture:
    - x86_64
    - aarch64
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ca-certificates-bundle
      - ruby-3.2
      - ruby3.2-ast~2.4.2

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
      - https://packages.cgr.dev/extras/chainguard-extras.rsa.pub
      - /work/packages/melange.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
      - https://packages.cgr.dev/extras
      - '@local /work/packages'
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ragel
      - ruby-3.2
      - ruby-3.2-dev
      - ruby3.2-bundler
      - ruby3.2-ast~2.4.2@local
      - ruby3.2-cliver~0.3.2@local
      - ruby3.2-simplecov~0.15.1@local

vars:
  gem: parser

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 0be420260b538ead5a9b9338172b6943b0babd73
      repository: https://github.com/whitequark/parser.git
      tag: v${{package.version}}

  - runs: |
      rake

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean
