package:
  name: ruby3.2-parseconfig
  version: 1.0.8
  epoch: 0
  description: ParseConfig provides simple parsing of standard configuration files.
  target-architecture:
    - x86_64
    - aarch64
  copyright:
    - license: MIT
  options:
    # See https://github.com/chainguard-dev/melange/blob/main/docs/BUILD-FILE.md
    no-provides: false
    no-depends: false
    no-commands: false
  dependencies:
    runtime:
      - ca-certificates-bundle
      - ruby-3.2

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
      - https://packages.cgr.dev/extras/chainguard-extras.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
      - https://packages.cgr.dev/extras
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev
      - ruby3.2-bundler

vars:
  gem: parseconfig

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 08ca6679a12adad6243a5ce6cd74836d6acf4f0c
      repository: https://github.com/datafolklabs/ruby-parseconfig.git
      branch: stable/1.0.x

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean
