package:
  name: ruby3.2-simplecov-html
  version: 0.10.2
  epoch: 0
  description: Default HTML formatter for SimpleCov code coverage tool for ruby 2.4+.
  target-architecture:
    - x86_64
    - aarch64
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ca-certificates-bundle
      - ruby-3.2

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
      - https://packages.cgr.dev/extras/chainguard-extras.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
      - https://packages.cgr.dev/extras
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev
      - ruby3.2-bundler

vars:
  gem: simplecov-html

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 31b2d514a3353a793104f335fac3860ac8f9d37a
      repository: https://github.com/simplecov-ruby/simplecov-html.git
      tag: v${{package.version}}

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean
