package:
  name: ruby3.2-rb_sys
  version: 0.9.98
  epoch: 0
  description: Make building native Ruby extensions in Rust easier than it would be in C. If it's not easy, it's a bug..
  target-architecture:
    - x86_64
    - aarch64
  copyright:
    - license: MIT
  options:
    # See https://github.com/chainguard-dev/melange/blob/main/docs/BUILD-FILE.md
    no-provides: false
    no-depends: false
    no-commands: false
  dependencies:
    runtime:
      - ca-certificates-bundle
      - ruby-3.2

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
      - https://packages.cgr.dev/extras/chainguard-extras.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
      - https://packages.cgr.dev/extras
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev
      - ruby3.2-bundler
  environment:
    RUBYGEMS_FORCE_DISABLE_GEM_SIGNING: true

vars:
  gem: rb_sys

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 06135a2476af3a239f189192f9e49a95b859c736
      repository: https://github.com/oxidize-rb/rb-sys.git
      tag: v${{package.version}}

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}
      dir: gem

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      dir: gem
      version: ${{package.version}}

  - uses: ruby/clean
