package:
  name: ruby3.2-terminal-table
  version: 3.0.2
  epoch: 0
  description: Terminal Table is a fast and simple, yet feature rich table generator written in Ruby.
  target-architecture:
    - x86_64
    - aarch64
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ca-certificates-bundle
      - ruby-3.2
      - ruby3.2-unicode-display_width

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
      - https://packages.cgr.dev/extras/chainguard-extras.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
      - https://packages.cgr.dev/extras
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev
      - ruby3.2-bundler

vars:
  gem: terminal-table

pipeline:
  - uses: git-checkout
    with:
      expected-commit: cb31efbff5f6e00091944aa90b76190221087b9f
      repository: https://github.com/tj/terminal-table.git
      tag: v${{package.version}}

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean
