package:
  name: ruby3.2-simplecov_json_formatter
  version: 0.1.4
  epoch: 0
  description: Default json_formatter formatter for SimpleCov code coverage tool for ruby 2.4+.
  target-architecture:
    - x86_64
    - aarch64
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ca-certificates-bundle
      - ruby-3.2

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
      - https://packages.cgr.dev/extras/chainguard-extras.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
      - https://packages.cgr.dev/extras
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev
      - ruby3.2-bundler

vars:
  gem: simplecov_json_formatter

pipeline:
  - uses: git-checkout
    with:
      expected-commit: a03461117e6a837ca68c08fba98852819664f66a
      repository: https://github.com/codeclimate-community/simplecov_json_formatter.git
      tag: ${{package.version}}

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean
