package:
  name: ruby3.2-rest-client
  version: 2.1.0
  epoch: 0
  description: A simple HTTP and REST client for Ruby, inspired by the Sinatra's microframework style of specifying actions get, put, post, delete.
  target-architecture:
    - x86_64
    - aarch64
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ca-certificates-bundle
      - ruby-3.2
      - ruby3.2-http-accept<2.0
      - ruby3.2-http-cookie<2.0
      - ruby3.2-mime-types<4.0
      - ruby3.2-netrc

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
      - https://packages.cgr.dev/extras/chainguard-extras.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
      - https://packages.cgr.dev/extras
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev
      - ruby3.2-bundler

vars:
  gem: rest-client

pipeline:
  - uses: git-checkout
    with:
      expected-commit: cf3e5a115bcdb8f3344aeac0e45b44d67fac1a42
      repository: https://github.com/rest-client/rest-client.git
      tag: v${{package.version}}

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean
