package:
  name: ruby3.2-opentelemetry-api
  version: 1.2.5
  epoch: 0
  description: A stats collection and distributed tracing framework.
  target-architecture:
    - x86_64
    - aarch64
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ca-certificates-bundle
      - ruby-3.2

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
      - https://packages.cgr.dev/extras/chainguard-extras.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
      - https://packages.cgr.dev/extras
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev
      - ruby3.2-bundler

vars:
  gem: opentelemetry-api

pipeline:
  - uses: git-checkout
    with:
      expected-commit: a0b535febb7a4fd36efd786235d73cba4dc091b1
      repository: https://github.com/open-telemetry/opentelemetry-ruby.git
      tag: ${{vars.gem}}/v${{package.version}}

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}
      dir: api

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}
      dir: api

  - uses: ruby/clean
