package:
  name: ruby3.2-commonmarker
  version: 0.23.6
  epoch: 0
  description: Ruby wrapper for Rust's comrak crate.
  target-architecture:
    - x86_64
    - aarch64
  copyright:
    - license: MIT
  options:
    # See https://github.com/chainguard-dev/melange/blob/main/docs/BUILD-FILE.md
    no-provides: false
    no-depends: false
    no-commands: false
  dependencies:
    runtime:
      - ca-certificates-bundle
      - ruby-3.2
      - ruby3.2-rb_sys

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
      - https://packages.cgr.dev/extras/chainguard-extras.rsa.pub
      - /work/packages/melange.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
      - https://packages.cgr.dev/extras
      - '@local /work/packages'
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - clang
      - curl
      - git
      - ruby-3.2
      - ruby-3.2-dev
      - ruby3.2-bundler
      - ruby3.2-rb_sys@local

vars:
  gem: commonmarker

pipeline:
  - uses: git-checkout
    with:
      expected-commit: a8f8d76fbc8c92ddb2e539a06bd93c5f8326705e
      repository: https://github.com/gjtorikian/commonmarker.git
      tag: v${{package.version}}

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean
